export const  ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const  ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const  ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE';

export const  LOGIN_REQUEST = 'LOGIN_REQUEST';
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const  LOGIN_FAILURE = 'LOGIN_FAILURE';

export const  LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const  LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const  LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const  ORDER_REQUEST = 'ORDER_REQUEST';
export const  ORDER_SUCCESS = 'ORDER_SUCCESS';
export const  ORDER_FAILURE = 'ORDER_FAILURE';

export const  ALL_USERS_REQUEST = 'ALL_USERS_REQUEST';
export const  ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const  ALL_USERS_FAILURE = 'ALL_USERS_FAILURE';

export const  ALL_SELLER_REQUEST = 'ALL_SELLER_REQUEST';
export const  ALL_SELLER_SUCCESS = 'ALL_SELLERS_SUCCESS';
export const  ALL_SELLER_FAILURE = 'ALL_SELLER_FAILURE';

export const  ALL_BUYER_REQUEST = 'ALL_BUYER_REQUEST';
export const  ALL_BUYER_SUCCESS = 'ALL_BUYER_SUCCESS';
export const  ALL_BUYER_FAILURE = 'ALL_BUYER_FAILURE'

export const  PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const  PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const  PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE';


export const  PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const  PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const  PRODUCT_DELETE_FAILURE = 'PRODUCT_DELETE_FAILURE'
export const  PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET'



export const CLEAR_ERRORS = 'CLEAR_ERRORS';
